### ISSUE TITLE
with_entries not implemented

### ISSUE THREAD

**Issue by danlange** [eiiches/jackson-jq#30]
The README lists "to_entries, from_entries, with_entries" on the implemented features list. When I try to use with_entries, I get the exception "net.thisptr.jackson.jq.exception.JsonQueryException: Function with_entries/1 does not exist".  Also, there is no WithEntriesFunction.java in https://github.com/eiiches/jackson-jq/tree/develop/jackson-jq/src/main/java/net/thisptr/jackson/jq/internal/functions.

I assume that this is just an oversight, since according to the jq documentation, with_entries is just "with_entries(foo) is a shorthand for to_entries | map(foo) | from_entries"

**Comment by danlange** [comment]
When I tried changing my "with_entries(foo)" to "to_entries | map(foo) | from_entries", I get the exception:
net.thisptr.jackson.jq.exception.JsonQueryException: Function to_entries/0 does not exist
        at net.thisptr.jackson.jq.internal.tree.FunctionCall.apply(FunctionCall.java:25)
        at net.thisptr.jackson.jq.internal.tree.binaryop.assignment.UpdateAssignment$1.apply(UpdateAssignment.java:36)
        at net.thisptr.jackson.jq.internal.misc.JsonNodeUtils.mutate(JsonNodeUtils.java:119)
        at net.thisptr.jackson.jq.internal.misc.JsonNodeUtils.mutate(JsonNodeUtils.java:183)
        at net.thisptr.jackson.jq.internal.tree.binaryop.assignment.UpdateAssignment.apply(UpdateAssignment.java:34)
        at net.thisptr.jackson.jq.internal.tree.PipedQuery.applyRecursive(PipedQuery.java:42)
        at net.thisptr.jackson.jq.internal.tree.PipedQuery.applyRecursive(PipedQuery.java:55)
        at net.thisptr.jackson.jq.internal.tree.PipedQuery.applyRecursive(PipedQuery.java:55)
        at net.thisptr.jackson.jq.internal.tree.PipedQuery.apply(PipedQuery.java:25)
        at net.thisptr.jackson.jq.internal.IsolatedScopeQuery.apply(IsolatedScopeQuery.java:21)

**Comment by danlange** [comment]
Thanks, it is working now.
I needed to add: 
scope.loadFunctions(Scope.class.getClassLoader());

You might want to improve the documentation, and/or add a convenience function:
Scope.newScopeWithBuiltinFunctions()

Actually, you might want to consider separating variables and functions into two separate objects.
I assume that the reason that scopes do not include the builtin functions by default is to avoid the performance penalty of using reflection to scan the classloader for functions.  Having an interface where the query is compiled in advance, and a scope is injected into it for every invocation encourages users to create a new scope for every invocation, resulting in the opposite effect on performance than was intended.

Anyway, thanks for your help, and thanks for creating jackson-jq!
