### ISSUE TITLE
JsonQueryException: Function tostring/0 does not exist

### ISSUE THREAD

**Issue by lalithkota** [eiiches/jackson-jq#363]
I am unable to use jq tostring function. I can see that tostring [is supported](https://github.com/eiiches/jackson-jq/tree/develop/1.x?tab=readme-ov-file#list-of-features). What am I doing wrong?

#### Java

```
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import net.thisptr.jackson.jq.BuiltinFunctionLoader;
import net.thisptr.jackson.jq.JsonQuery;
import net.thisptr.jackson.jq.Scope;
import net.thisptr.jackson.jq.Version;
import net.thisptr.jackson.jq.Versions;
import net.thisptr.jackson.jq.exception.JsonQueryException;
import net.thisptr.jackson.jq.module.loaders.BuiltinModuleLoader;

public class TestJacksonJq {
    public static void main(String[] argv) throws JsonQueryException, JsonProcessingException{
        ObjectMapper objectMapper = new ObjectMapper();
        Scope scope = Scope.newEmptyScope();
        BuiltinFunctionLoader.getInstance().loadFunctions(Versions.JQ_1_6, scope);
        scope.setModuleLoader(BuiltinModuleLoader.getInstance());
        JsonQuery jqQuery = JsonQuery.compile(".payload | tostring", Versions.JQ_1_6);
        
        String input = "{\"payload\": {\"abc\": 123}}";
        JsonNode inputNode = objectMapper.readTree(input);
        
        List<JsonNode> outputNodes = new ArrayList<>();
        jqQuery.apply(scope, inputNode, outputNodes::add);
        System.out.println("Returned value: " + outputNodes.get(0).asText());
    }
}
```

#### Stack trace

```
Exception in thread "main" net.thisptr.jackson.jq.exception.JsonQueryException: Function tostring/0 does not exist
	at net.thisptr.jackson.jq.internal.tree.FunctionCall.lookupFunction(FunctionCall.java:49)
	at net.thisptr.jackson.jq.internal.tree.FunctionCall.apply(FunctionCall.java:55)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.pathRecursive(PipedQuery.java:52)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.lambda$pathRecursive$2(PipedQuery.java:53)
	at net.thisptr.jackson.jq.path.ObjectFieldPath.resolve(ObjectFieldPath.java:83)
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.FieldAccess.emitObjectFieldPath(FieldAccess.java:56)
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.IdentifierFieldAccess.lambda$apply$0(IdentifierFieldAccess.java:35)
	at net.thisptr.jackson.jq.internal.tree.ThisObject.apply(ThisObject.java:20)
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.IdentifierFieldAccess.apply(IdentifierFieldAccess.java:34)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.pathRecursive(PipedQuery.java:52)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.apply(PipedQuery.java:25)
	at net.thisptr.jackson.jq.internal.IsolatedScopeQuery.apply(IsolatedScopeQuery.java:21)
	at net.thisptr.jackson.jq.Expression.apply(Expression.java:11)
	at net.thisptr.jackson.jq.JsonQuery.apply(JsonQuery.java:17)
	at TestJacksonJq.main(TestJacksonJq.java:28)
```

#### pom.xml

<details>
    <summary>pom.xml</summary>

    <?xml version="1.0" encoding="UTF-8"?>

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion>

        <groupId>test.jacksonjq</groupId>
        <artifactId>test-jackson-jq</artifactId>
        <name>Test Jackson Jq</name>
        <version>0.0.1-SNAPSHOT</version>

        <properties>
            <java.version>1.8</java.version>
            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
            <maven.compiler.source>${java.version}</maven.compiler.source>
            <maven.compiler.target>${java.version}</maven.compiler.target>
        </properties>

        <dependencies>
            <dependency>
                <groupId>net.thisptr</groupId>
                <artifactId>jackson-jq</artifactId>
                <version>1.0.0</version>
            </dependency>
        </dependencies>

        <build>
            <plugins>
                <plugin>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>3.1.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.0</version>
                </plugin>

                <plugin>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.0.2</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>3.6.0</version>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>shade</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <createDependencyReducedPom>false</createDependencyReducedPom>
                        <transformers>
                            <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                <mainClass>TestJacksonJq</mainClass>
                            </transformer>
                        </transformers>
                        <filters>
                            <filter>
                                <artifact>*:*</artifact>
                                <excludes>
                                    <exclude>META-INF/**</exclude>
                                    <exclude>META-INF</exclude>
                                    <exclude>module-info.class</exclude>
                                </excludes>
                            </filter>
                        </filters>
                    </configuration>
                </plugin>
            </plugins>
        </build>
    </project>
</details>

**Comment by lalithkota** [comment]
Is this because of improper shaded jar? Like https://github.com/eiiches/jackson-jq/issues/82.

**Comment by lalithkota** [comment]
I can confirm that this is working after changing the shade plugin config, as given in #82.
So, I'm closing this.

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>3.6.0</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>shade</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <createDependencyReducedPom>false</createDependencyReducedPom>
        <transformers>
            <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                <mainClass>TestJacksonJq</mainClass>
            </transformer>
            <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                <resource>net/thisptr/jackson/jq/jq.json</resource>
            </transformer>
            <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
        </transformers>
        <filters>
            <filter>
                <artifact>*:*</artifact>
                <excludes>
                    <exclude>META-INF/*LICENSE*</exclude>
                    <exclude>META-INF/*NOTICE*</exclude>
                    <exclude>META-INF/*DEPENDENCIES*</exclude>
                    <exclude>META-INF/*MANIFEST*</exclude>
                    <exclude>**/module-info.class</exclude>
                </excludes>
            </filter>
        </filters>
    </configuration>
</plugin>
```
