### ISSUE TITLE
Function length/0 does not exist

### ISSUE THREAD

**Issue by znerd** [eiiches/jackson-jq#48]
I have a very simple JQ filter like this:
```
.scores|length
```

And then I have a simple JSON like this:
```
{ "scores":  [ 0, 1, 2, 3 ] }
```

When I to apply the query, I get an exception though, with this message:
```
Function length/0 does not exist
``` 

Stack trace:
```
Caused by: net.thisptr.jackson.jq.exception.JsonQueryException: Function length/0 does not exist
	at net.thisptr.jackson.jq.internal.tree.FunctionCall.apply(FunctionCall.java:30)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.pathRecursive(PipedQuery.java:52)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.lambda$pathRecursive$2(PipedQuery.java:53)
	at net.thisptr.jackson.jq.path.ObjectFieldPath.resolve(ObjectFieldPath.java:83)
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.FieldAccess.emitObjectFieldPath(FieldAccess.java:55)
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.IdentifierFieldAccess.lambda$apply$0(IdentifierFieldAccess.java:35)
	at net.thisptr.jackson.jq.internal.tree.ThisObject.apply(ThisObject.java:20)
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.IdentifierFieldAccess.apply(IdentifierFieldAccess.java:34)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.pathRecursive(PipedQuery.java:52)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.apply(PipedQuery.java:25)
	at net.thisptr.jackson.jq.internal.IsolatedScopeQuery.apply(IsolatedScopeQuery.java:21)
	at net.thisptr.jackson.jq.Expression.apply(Expression.java:11)
	at net.thisptr.jackson.jq.JsonQuery.apply(JsonQuery.java:17)
```

I'm using a Maven project, with these dependencies defined:
```
        <dependency>
            <groupId>net.thisptr</groupId>
            <artifactId>jackson-jq</artifactId>
            <version>1.0.0-preview.20190925</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.9.10</version>
        </dependency>
```

Any hints would be appreciated.

**Comment by znerd** [comment]
Using the CLI it does work:
```
$ java -jar jackson-jq-cli-1.0.0-preview.20190925.jar '.scores|length'
{ "scores":  [ 0, 1, 2, 3 ] }
4
```

**Comment by znerd** [comment]
I resolved the problem by looking at the source code for the CLI program. We need to enable the built-in functions explicitly:

```
BuiltinFunctionLoader.getInstance().loadFunctions(version, scope);
```

See:
- https://github.com/eiiches/jackson-jq/blob/develop/1.x/jackson-jq-cli/src/main/java/net/thisptr/jackson/jq/cli/Main.java

Now it works. Issue resolved.
