### ISSUE TITLE
"Formatting operator @csv does not exist" when using in Groovy

### ISSUE THREAD

**Issue by bbarany** [eiiches/jackson-jq#53]
Hi,

I'm trying to integrate jackson-jq 0.0.12 with RapidMiner using Groovy scripting.
(Branch 1.x is marked with unstable API, should I rather use that?)

The script is more or less identical to Main.java in jackson-jq-cli. It works well, converting JSON to JSON. However, I get an exception when trying to convert to CSV: 

The scripting engine Groovy reported an error in the script: net.thisptr.jackson.jq.exception.JsonQueryException: Formatting operator @csv does not exist. 

Caused by: net.thisptr.jackson.jq.exception.JsonQueryException: Formatting operator @csv does not exist
        at net.thisptr.jackson.jq.internal.tree.FormattingFilter.apply(FormattingFilter.java:24)
        at net.thisptr.jackson.jq.internal.tree.PipedQuery.applyRecursive(PipedQuery.java:42)
        at net.thisptr.jackson.jq.internal.tree.PipedQuery.applyRecursive(PipedQuery.java:55)
        at net.thisptr.jackson.jq.internal.tree.PipedQuery.applyRecursive(PipedQuery.java:55)
        at net.thisptr.jackson.jq.internal.tree.PipedQuery.applyRecursive(PipedQuery.java:55)
        at net.thisptr.jackson.jq.internal.tree.PipedQuery.applyRecursive(PipedQuery.java:55)
        at net.thisptr.jackson.jq.internal.tree.PipedQuery.apply(PipedQuery.java:25)
        at net.thisptr.jackson.jq.internal.IsolatedScopeQuery.apply(IsolatedScopeQuery.java:21)
        at net.thisptr.jackson.jq.JsonQuery.apply(JsonQuery.java:21)
        at net.thisptr.jackson.jq.JsonQuery$apply$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)

Do you have an idea if this is supposed to work, and how?

Thanks for creating jackson-jq!

**Comment by eiiches** [comment]
Sorry I couldn't help here at the time. My guess is that jq.json isn't properly loaded due to class loader problems, etc. Anyway, if you still need help, please feel free to reopen.
