### ISSUE TITLE
null slice index

### ISSUE THREAD

**Issue by kszafran** [eiiches/jackson-jq#55]
Hey, I think I found another inconsistency with original jq. I'm using 0.0.11, perhaps it works correctly in the 1.0.0 preview (I haven't checked that).

jq 1.6:
```
$ jq -n '"test" | .[1:null]'
"est"
```

jackson-jq 0.0.11:
```
Exception in thread "main" net.thisptr.jackson.jq.exception.JsonQueryException: Start and end indices of an string slice must be numbers
	at net.thisptr.jackson.jq.exception.JsonQueryException.format(JsonQueryException.java:35)
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.BracketFieldAccess.resolveFieldAccess(BracketFieldAccess.java:62)
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.FieldAccess.apply(FieldAccess.java:40)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.applyRecursive(PipedQuery.java:42)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.applyRecursive(PipedQuery.java:55)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.apply(PipedQuery.java:25)
	at net.thisptr.jackson.jq.internal.IsolatedScopeQuery.apply(IsolatedScopeQuery.java:21)
...
```

**Comment by eiiches** [comment]
Thanks for reporting this. I'm closing this for now as the issue seems to be fixed in `1.0.0-preview.*`. Feel free to reopen if you still need this fixed in 0.x versions.
