### ISSUE TITLE
Shadow JAR causes exception

### ISSUE THREAD

**Issue by larryguo** [eiiches/jackson-jq#82]
I used build 1.0.0-preview.20210610 with my Java project and it runs well with Intellij or Gradle cli. However, when I try to run the exact same task using fat jar (built by 'com.github.johnrengelman.shadow' v5.2.0), the JsonQuery.apply will throw Exception:
` net.thisptr.jackson.jq.exception.JsonQueryException: Function empty/0 does not exist
	at net.thisptr.jackson.jq.internal.tree.FunctionCall.apply(FunctionCall.java:30) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.Conditional.lambda$pathRecursive$0(Conditional.java:33) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.Output.emit(Output.java:14) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.binaryop.SimpleBinaryOperatorExpression.lambda$null$0(SimpleBinaryOperatorExpression.java:24) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.Output.emit(Output.java:14) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.path.ObjectFieldPath.resolve(ObjectFieldPath.java:83) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.FieldAccess.emitObjectFieldPath(FieldAccess.java:55) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.IdentifierFieldAccess.lambda$apply$0(IdentifierFieldAccess.java:35) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.ThisObject.apply(ThisObject.java:20) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.IdentifierFieldAccess.apply(IdentifierFieldAccess.java:34) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.Expression.apply(Expression.java:11) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.binaryop.SimpleBinaryOperatorExpression.lambda$apply$1(SimpleBinaryOperatorExpression.java:23) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.Output.emit(Output.java:14) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.StringInterpolation.recurse(StringInterpolation.java:45) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.StringInterpolation.apply(StringInterpolation.java:30) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.Expression.apply(Expression.java:11) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.binaryop.SimpleBinaryOperatorExpression.apply(SimpleBinaryOperatorExpression.java:22) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.FixedScopeQuery.apply(FixedScopeQuery.java:22) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.JsonQueryFunction.pathRecursive(JsonQueryFunction.java:42) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.JsonQueryFunction.apply(JsonQueryFunction.java:37) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.FunctionCall.apply(FunctionCall.java:31) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.Expression.apply(Expression.java:11) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.Conditional.pathRecursive(Conditional.java:26) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.Conditional.apply(Conditional.java:41) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.IsolatedScopeQuery.apply(IsolatedScopeQuery.java:21) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.JsonQueryFunction.pathRecursive(JsonQueryFunction.java:42) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.JsonQueryFunction.pathRecursive(JsonQueryFunction.java:53) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.JsonQueryFunction.apply(JsonQueryFunction.java:37) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.FunctionCall.apply(FunctionCall.java:31) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.IdentifierFieldAccess.apply(IdentifierFieldAccess.java:34) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.pathRecursive(PipedQuery.java:52) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.lambda$pathRecursive$2(PipedQuery.java:53) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.FieldAccess.emitAllPath(FieldAccess.java:39) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.BracketExtractFieldAccess.lambda$apply$0(BracketExtractFieldAccess.java:24) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.path.ObjectFieldPath.resolve(ObjectFieldPath.java:83) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.FieldAccess.emitObjectFieldPath(FieldAccess.java:55) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.IdentifierFieldAccess.lambda$apply$0(IdentifierFieldAccess.java:35) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.ThisObject.apply(ThisObject.java:20) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.IdentifierFieldAccess.apply(IdentifierFieldAccess.java:34) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.BracketExtractFieldAccess.apply(BracketExtractFieldAccess.java:23) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.pathRecursive(PipedQuery.java:52) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.apply(PipedQuery.java:25) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.internal.IsolatedScopeQuery.apply(IsolatedScopeQuery.java:21) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.Expression.apply(Expression.java:11) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at net.thisptr.jackson.jq.JsonQuery.apply(JsonQuery.java:17) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at util.JacksonJq.getNodes(JacksonJq.java:22) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]
	at util.JacksonJq.toString(JacksonJq.java:27) ~[scdt-injector-2.2.0-dev.30.uncommitted-1d032ac.jar:?]`

Here is the related code segment:
`
public class JacksonJq {
  private static final Scope ROOT_SCOPE = Scope.newEmptyScope();
  static {
    BuiltinFunctionLoader.getInstance().loadFunctions(Versions.JQ_1_6, ROOT_SCOPE);
  }

  public static List<JsonNode> getNodes(JsonNode jsonNode, String query) throws JsonQueryException {
    JsonQuery q = JsonQuery.compile(query, Versions.JQ_1_6);
    List<JsonNode> out = new ArrayList<>();
    q.apply(ROOT_SCOPE, jsonNode, out::add);
    return out;
  }
`

**Comment by eiiches** [comment]
You probably have an incomplete [ServiceLoader](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html) provider configuration due to the shadow plugin. Can you make sure that `META-INF/services/net.thisptr.jackson.jq.Function` in the fat jar contains `net.thisptr.jackson.jq.internal.functions.EmptyFunction` row?

```console
$ unzip THE_FAT_JAR.jar META-INF/services/net.thisptr.jackson.jq.Function
$ grep Empty META-INF/services/net.thisptr.jackson.jq.Function
net.thisptr.jackson.jq.internal.functions.EmptyFunction
```

If the row is missing, you need to configure the shadow plugin to merge (and not overwrite as it probably does by default) multiple provider configurations from different jars. I don't know how to do it in Gradle, but the Maven equivalent is:

https://github.com/eiiches/jackson-jq/blob/9fee69d33bc6c876894a96b3d178df02cde0acb6/jackson-jq-cli/pom.xml#L48-L51

**Comment by eiiches** [comment]
```gradle
shadowJar {
  mergeServiceFiles()
}
```
https://imperceptiblethoughts.com/shadow/configuration/merging/#merging-service-descriptor-files

**Comment by eiiches** [comment]
You also need to merge `net/thisptr/jackson/jq/jq.json`. According to the documentation, something like below should work.

```gradle
shadowJar {
  append 'net/thisptr/jackson/jq/jq.json'
}
```

https://imperceptiblethoughts.com/shadow/configuration/merging/#appending-text-files
